apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoApp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: demoApp
        image: 106490669391.dkr.ecr.us-east-1.amazonaws.com/rep_lab:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
            
---
apiVersion: v1
kind: Service 
metadata:
  name: demoApp
  labels:
    app: demoApp
spec:
  selector:
    app: demoApp
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 8080
    targetPort: 8080
